artifacts:
  "@daiyam/artifact-lang-ts":
    version: 0.6.3
  "@daiyam/artifact-npm":
    version: 0.6.2
  "@daiyam/artifact-npm-ts":
    version: 0.4.3
  "@daiyam/artifact-npm-lib-ts":
    version: 0.2.6
  "@daiyam/artifact-npm-zokugun":
    version: 0.2.2
  "@daiyam/artifact-test-vitest-ts":
    version: 0.2.4
  "@daiyam/artifact-gh-issuehub":
    version: 0.2.2
  "@daiyam/artifact-lang-js":
    version: 0.9.3
    requires:
      - "24"
