/* eslint-disable import/order,import/no-duplicates */
import { Dir } from './types/dir.js';
import { typeExports } from './types/exports.js';
import type { FsResult, FsVoidResult } from './types/exports.js';
import { FileHandle } from './types/file-handle.js';
import { FsError } from './types/fs-error.js';
import { type ReadStreamOptions, type WriteStreamOptions } from './types/stream.js';
import { type WalkItem, type WalkOptions } from './types/walk.js';
import { isFsError } from './utils/is-fs-error.js';

import {
	access,
	appendFile,
	chmod,
	chown,
	close,
	copyFile,
	cp,
	exists,
	fchmod,
	fchown,
	fdatasync,
	fstat,
	fsync,
	ftruncate,
	futimes,
	glob,
	lchmod,
	lchown,
	link,
	lstat,
	lutimes,
	mkdir,
	mkdtemp,
	mkdtempDisposable,
	open,
	openAsBlob,
	read,
	readv,
	readFile,
	readdir,
	readlink,
	realpath,
	rename,
	rm,
	rmdir,
	stat,
	statfs,
	symlink,
	truncate,
	unlink,
	utimes,
	write,
	writev,
	writeFile,
} from './fs/async.js';
import { copy } from './copy/async.js';
import { createFile, ensureFile } from './create-file/async.js';
import { createLink, ensureLink } from './create-link/async.js';
import { createReadStream } from './create-read-stream/index.js';
import { createSymlink, ensureSymlink } from './create-symlink/async.js';
import { createWriteStream } from './create-write-stream/index.js';
import { emptyDir, emptydir } from './empty-dir/async.js';
import { isDir } from './is-dir/async.js';
import { isEmptyDir } from './is-empty-dir/async.js';
import { isEmptyFile } from './is-empty-file/async.js';
import { isExisting } from './is-existing/async.js';
import { isFile } from './is-file/async.js';
import { isLink } from './is-link/async.js';
import { isNonEmptyDir } from './is-non-empty-dir/async.js';
import { isNonEmptyFile } from './is-non-empty-file/async.js';
import { isSymlink } from './is-symlink/async.js';
import { ensureDir, mkdirp, mkdirs } from './make-dir/async.js';
import { move } from './move/async.js';
import { openAsHandle } from './open-as-handle/async.js';
import { openDir, opendir } from './open-dir/async.js';
import { outputFile } from './output-file/async.js';
import { outputJSON, outputJson } from './output-json/async.js';
import { pathExists } from './path-exists/async.js';
import { readJSON, readJson } from './read-json/async.js';
import { remove } from './remove/async.js';
import { touch } from './touch/async.js';
import { walk } from './walk/async.js';
import { writeJSON, writeJson } from './write-json/async.js';

/* eslint-disable unicorn/prefer-export-from */
export {
	type FsResult,
	type FsVoidResult,
	type ReadStreamOptions,
	type WriteStreamOptions,
	type WalkItem,
	type WalkOptions,
	Dir,
	FileHandle,
	FsError,
	access,
	appendFile,
	chmod,
	chown,
	close,
	copy,
	copyFile,
	cp,
	createFile,
	createLink,
	createReadStream,
	createSymlink,
	createWriteStream,
	emptyDir,
	emptydir,
	ensureDir,
	ensureFile,
	ensureLink,
	ensureSymlink,
	exists,
	fchmod,
	fchown,
	fdatasync,
	fstat,
	fsync,
	ftruncate,
	futimes,
	glob,
	isDir,
	isEmptyDir,
	isEmptyFile,
	isExisting,
	isFile,
	isFsError,
	isLink,
	isNonEmptyDir,
	isNonEmptyFile,
	isSymlink,
	lchmod,
	lchown,
	link,
	lstat,
	lutimes,
	mkdir,
	mkdirp,
	mkdirs,
	mkdtemp,
	mkdtempDisposable,
	move,
	open,
	openAsBlob,
	openAsHandle,
	openDir,
	opendir,
	outputFile,
	outputJSON,
	outputJson,
	pathExists,
	read,
	readdir,
	readFile,
	readJSON,
	readJson,
	readlink,
	readv,
	realpath,
	remove,
	rename,
	rm,
	rmdir,
	stat,
	statfs,
	symlink,
	touch,
	truncate,
	unlink,
	utimes,
	walk,
	write,
	writev,
	writeFile,
	writeJSON,
	writeJson,
};
/* eslint-enable unicorn/prefer-export-from */

// eslint-disable-next-line import/no-anonymous-default-export
export default {
	...typeExports,
	Dir,
	FileHandle,
	FsError,
	access,
	appendFile,
	chmod,
	chown,
	close,
	copyFile,
	cp,
	createFile,
	createLink,
	createReadStream,
	createSymlink,
	createWriteStream,
	emptyDir,
	emptydir,
	ensureDir,
	ensureFile,
	exists,
	fchmod,
	fchown,
	fdatasync,
	fstat,
	fsync,
	ftruncate,
	futimes,
	glob,
	isDir,
	isEmptyDir,
	isEmptyFile,
	isExisting,
	isFile,
	isFsError,
	isLink,
	isNonEmptyDir,
	isNonEmptyFile,
	isSymlink,
	lchmod,
	lchown,
	link,
	lstat,
	lutimes,
	mkdir,
	mkdirp,
	mkdirs,
	mkdtemp,
	mkdtempDisposable,
	open,
	openAsBlob,
	openAsHandle,
	opendir,
	outputFile,
	outputJSON,
	outputJson,
	pathExists,
	read,
	readdir,
	readFile,
	readJSON,
	readJson,
	readlink,
	readv,
	realpath,
	remove,
	rename,
	rm,
	rmdir,
	stat,
	statfs,
	symlink,
	touch,
	truncate,
	unlink,
	utimes,
	walk,
	write,
	writev,
	writeFile,
	writeJSON,
	writeJson,
};
