/* eslint-disable import/order,import/no-duplicates */
import * as mode from './mode/index.js';
import { Dir } from './types/dir.js';
import { typeExports } from './types/exports.js';
import type { FsResult, FsVoidResult } from './types/exports.js';
import { FileHandle } from './types/file-handle.js';
import { FsError } from './types/fs-error.js';
import { type ReadStreamOptions, type WriteStreamOptions } from './types/stream.js';
import { type WalkItem, type WalkOptions } from './types/walk.js';
import { isFsError } from './utils/is-fs-error.js';

import {
	access as accessAsync,
	appendFile as appendFileAsync,
	chmod as chmodAsync,
	chown as chownAsync,
	close as closeAsync,
	copyFile as copyFileAsync,
	cp as cpAsync,
	exists as existsAsync,
	fchmod as fchmodAsync,
	fchown as fchownAsync,
	fdatasync as fdatasyncAsync,
	fstat as fstatAsync,
	fsync as fsyncAsync,
	ftruncate as ftruncateAsync,
	futimes as futimesAsync,
	glob as globAsync,
	lchmod as lchmodAsync,
	lchown as lchownAsync,
	link as linkAsync,
	lstat as lstatAsync,
	lutimes as lutimesAsync,
	mkdir as mkdirAsync,
	mkdtemp as mkdtempAsync,
	mkdtempDisposable as mkdtempDisposableAsync,
	open as openAsync,
	openAsBlob as openAsBlobAsync,
	read as readAsync,
	readv as readvAsync,
	readFile as readFileAsync,
	readdir as readdirAsync,
	readlink as readlinkAsync,
	realpath as realpathAsync,
	rename as renameAsync,
	rm as rmAsync,
	rmdir as rmdirAsync,
	stat as statAsync,
	statfs as statfsAsync,
	symlink as symlinkAsync,
	truncate as truncateAsync,
	unlink as unlinkAsync,
	utimes as utimesAsync,
	write as writeAsync,
	writev as writevAsync,
	writeFile as writeFileAsync,
} from './fs/async.js';
import { copy as copyAsync } from './copy/async.js';
import { createFile as createFileAsync, ensureFile as ensureFileAsync } from './create-file/async.js';
import { createLink as createLinkAsync, ensureLink as ensureLinkAsync } from './create-link/async.js';
import { createSymlink as createSymlinkAsync, ensureSymlink as ensureSymlinkAsync } from './create-symlink/async.js';
import { emptyDir as emptyDirAsync, emptydir as emptydirAsync } from './empty-dir/async.js';
import { isDir as isDirAsync } from './is-dir/async.js';
import { isEmptyDir as isEmptyDirAsync } from './is-empty-dir/async.js';
import { isEmptyFile as isEmptyFileAsync } from './is-empty-file/async.js';
import { isExisting as isExistingAsync } from './is-existing/async.js';
import { isFile as isFileAsync } from './is-file/async.js';
import { isLink as isLinkAsync } from './is-link/async.js';
import { isNonEmptyDir as isNonEmptyDirAsync } from './is-non-empty-dir/async.js';
import { isNonEmptyFile as isNonEmptyFileAsync } from './is-non-empty-file/async.js';
import { isSymlink as isSymlinkAsync } from './is-symlink/async.js';
import { ensureDir as ensureDirAsync, mkdirp as mkdirpAsync, mkdirs as mkdirsAsync } from './make-dir/async.js';
import { move as moveAsync } from './move/async.js';
import { openAsHandle as openAsHandleAsync } from './open-as-handle/async.js';
import { openDir as openDirAsync, opendir as opendirAsync, openDir as openDirSync, opendir as opendirSync } from './open-dir/async.js';
import { outputFile as outputFileAsync } from './output-file/async.js';
import { outputJSON as outputJSONAsync, outputJson as outputJsonAsync } from './output-json/async.js';
import { pathExists as pathExistsAsync } from './path-exists/async.js';
import { readJSON as readJSONAsync, readJson as readJsonAsync } from './read-json/async.js';
import { remove as removeAsync } from './remove/async.js';
import { touch as touchAsync } from './touch/async.js';
import { walk as walkAsync } from './walk/async.js';
import { writeJSON as writeJSONAsync, writeJson as writeJsonAsync } from './write-json/async.js';

import {
	access as accessSync,
	appendFile as appendFileSync,
	chmod as chmodSync,
	chown as chownSync,
	close as closeSync,
	copyFile as copyFileSync,
	cp as cpSync,
	exists as existsSync,
	fchmod as fchmodSync,
	fchown as fchownSync,
	fdatasync as fdatasyncSync,
	fstat as fstatSync,
	fsync as fsyncSync,
	ftruncate as ftruncateSync,
	futimes as futimesSync,
	glob as globSync,
	lchmod as lchmodSync,
	lchown as lchownSync,
	link as linkSync,
	lstat as lstatSync,
	lutimes as lutimesSync,
	mkdir as mkdirSync,
	mkdtemp as mkdtempSync,
	mkdtempDisposable as mkdtempDisposableSync,
	open as openSync,
	read as readSync,
	readv as readvSync,
	readFile as readFileSync,
	readdir as readdirSync,
	readlink as readlinkSync,
	realpath as realpathSync,
	rename as renameSync,
	rm as rmSync,
	rmdir as rmdirSync,
	stat as statSync,
	statfs as statfsSync,
	symlink as symlinkSync,
	truncate as truncateSync,
	unlink as unlinkSync,
	utimes as utimesSync,
	write as writeSync,
	writev as writevSync,
	writeFile as writeFileSync,
} from './fs/sync.js';
import { copy as copySync } from './copy/sync.js';
import { createFile as createFileSync, ensureFile as ensureFileSync } from './create-file/sync.js';
import { createLink as createLinkSync, ensureLink as ensureLinkSync } from './create-link/sync.js';
import { createSymlink as createSymlinkSync, ensureSymlink as ensureSymlinkSync } from './create-symlink/sync.js';
import { emptyDir as emptyDirSync, emptydir as emptydirSync } from './empty-dir/sync.js';
import { isDir as isDirSync } from './is-dir/sync.js';
import { isEmptyDir as isEmptyDirSync } from './is-empty-dir/sync.js';
import { isEmptyFile as isEmptyFileSync } from './is-empty-file/sync.js';
import { isExisting as isExistingSync } from './is-existing/sync.js';
import { isFile as isFileSync } from './is-file/sync.js';
import { isLink as isLinkSync } from './is-link/sync.js';
import { isNonEmptyDir as isNonEmptyDirSync } from './is-non-empty-dir/sync.js';
import { isNonEmptyFile as isNonEmptyFileSync } from './is-non-empty-file/sync.js';
import { isSymlink as isSymlinkSync } from './is-symlink/sync.js';
import { ensureDir as ensureDirSync, mkdirp as mkdirpSync, mkdirs as mkdirsSync } from './make-dir/sync.js';
import { move as moveSync } from './move/sync.js';
import { outputFile as outputFileSync } from './output-file/sync.js';
import { outputJSON as outputJSONSync, outputJson as outputJsonSync } from './output-json/sync.js';
import { pathExists as pathExistsSync } from './path-exists/sync.js';
import { readJSON as readJSONSync, readJson as readJsonSync } from './read-json/sync.js';
import { remove as removeSync } from './remove/sync.js';
import { touch as touchSync } from './touch/sync.js';
import { walk as walkSync } from './walk/sync.js';
import { writeJSON as writeJSONSync, writeJson as writeJsonSync } from './write-json/sync.js';

import { createReadStream } from './create-read-stream/index.js';
import { createWriteStream } from './create-write-stream/index.js';

/* eslint-disable unicorn/prefer-export-from */
export {
	type FsResult,
	type FsVoidResult,
	type ReadStreamOptions,
	type WriteStreamOptions,
	type WalkItem,
	type WalkOptions,
	Dir,
	FileHandle,
	FsError,
	mode,
	accessAsync,
	accessSync,
	appendFileAsync,
	appendFileSync,
	chmodAsync,
	chmodSync,
	chownAsync,
	chownSync,
	closeAsync,
	closeSync,
	copyAsync,
	copyFileAsync,
	copyFileSync,
	copySync,
	cpAsync,
	cpSync,
	createFileAsync,
	createFileSync,
	createLinkAsync,
	createLinkSync,
	createReadStream,
	createSymlinkAsync,
	createSymlinkSync,
	createWriteStream,
	emptyDirAsync,
	emptyDirSync,
	emptydirAsync,
	emptydirSync,
	ensureDirAsync,
	ensureDirSync,
	ensureFileAsync,
	ensureFileSync,
	ensureLinkAsync,
	ensureLinkSync,
	ensureSymlinkAsync,
	ensureSymlinkSync,
	existsAsync,
	existsSync,
	fchmodAsync,
	fchmodSync,
	fchownAsync,
	fchownSync,
	fdatasyncAsync,
	fdatasyncSync,
	fstatAsync,
	fstatSync,
	fsyncAsync,
	fsyncSync,
	ftruncateAsync,
	ftruncateSync,
	futimesAsync,
	futimesSync,
	globAsync,
	globSync,
	isDirAsync,
	isDirSync,
	isEmptyDirAsync,
	isEmptyDirSync,
	isEmptyFileAsync,
	isEmptyFileSync,
	isExistingAsync,
	isExistingSync,
	isFileAsync,
	isFileSync,
	isFsError,
	isLinkAsync,
	isLinkSync,
	isNonEmptyDirAsync,
	isNonEmptyDirSync,
	isNonEmptyFileAsync,
	isNonEmptyFileSync,
	isSymlinkAsync,
	isSymlinkSync,
	lchmodAsync,
	lchmodSync,
	lchownAsync,
	lchownSync,
	linkAsync,
	linkSync,
	lstatAsync,
	lstatSync,
	lutimesAsync,
	lutimesSync,
	mkdirAsync,
	mkdirSync,
	mkdirpAsync,
	mkdirpSync,
	mkdirsAsync,
	mkdirsSync,
	mkdtempAsync,
	mkdtempSync,
	mkdtempDisposableAsync,
	mkdtempDisposableSync,
	moveAsync,
	moveSync,
	openAsync,
	openSync,
	openAsBlobAsync,
	openAsHandleAsync,
	openDirAsync,
	openDirSync,
	opendirAsync,
	opendirSync,
	outputFileAsync,
	outputFileSync,
	outputJSONAsync,
	outputJSONSync,
	outputJsonAsync,
	outputJsonSync,
	pathExistsAsync,
	pathExistsSync,
	readAsync,
	readSync,
	readdirAsync,
	readdirSync,
	readFileAsync,
	readFileSync,
	readJSONAsync,
	readJSONSync,
	readJsonAsync,
	readJsonSync,
	readlinkAsync,
	readlinkSync,
	readvAsync,
	readvSync,
	realpathAsync,
	realpathSync,
	removeAsync,
	removeSync,
	renameAsync,
	renameSync,
	rmAsync,
	rmSync,
	rmdirAsync,
	rmdirSync,
	statAsync,
	statSync,
	statfsAsync,
	statfsSync,
	symlinkAsync,
	symlinkSync,
	touchAsync,
	touchSync,
	truncateAsync,
	truncateSync,
	unlinkAsync,
	unlinkSync,
	utimesAsync,
	utimesSync,
	walkAsync,
	walkSync,
	writeAsync,
	writeSync,
	writevAsync,
	writevSync,
	writeFileAsync,
	writeFileSync,
	writeJSONAsync,
	writeJSONSync,
	writeJsonAsync,
	writeJsonSync,
};
/* eslint-enable unicorn/prefer-export-from */

// eslint-disable-next-line import/no-anonymous-default-export
export default {
	...typeExports,
	Dir,
	FileHandle,
	FsError,
	mode,
	accessAsync,
	accessSync,
	appendFileAsync,
	appendFileSync,
	chmodAsync,
	chmodSync,
	chownAsync,
	chownSync,
	closeAsync,
	closeSync,
	copyAsync,
	copyFileAsync,
	copyFileSync,
	copySync,
	cpAsync,
	cpSync,
	createFileAsync,
	createFileSync,
	createLinkAsync,
	createLinkSync,
	createReadStream,
	createSymlinkAsync,
	createSymlinkSync,
	createWriteStream,
	emptyDirAsync,
	emptyDirSync,
	emptydirAsync,
	emptydirSync,
	ensureDirAsync,
	ensureDirSync,
	ensureFileAsync,
	ensureFileSync,
	ensureLinkAsync,
	ensureLinkSync,
	ensureSymlinkAsync,
	ensureSymlinkSync,
	existsAsync,
	existsSync,
	fchmodAsync,
	fchmodSync,
	fchownAsync,
	fchownSync,
	fdatasyncAsync,
	fdatasyncSync,
	fstatAsync,
	fstatSync,
	fsyncAsync,
	fsyncSync,
	ftruncateAsync,
	ftruncateSync,
	futimesAsync,
	futimesSync,
	globAsync,
	globSync,
	isDirAsync,
	isDirSync,
	isEmptyDirAsync,
	isEmptyDirSync,
	isEmptyFileAsync,
	isEmptyFileSync,
	isExistingAsync,
	isExistingSync,
	isFileAsync,
	isFileSync,
	isFsError,
	isLinkAsync,
	isLinkSync,
	isNonEmptyDirAsync,
	isNonEmptyDirSync,
	isNonEmptyFileAsync,
	isNonEmptyFileSync,
	isSymlinkAsync,
	isSymlinkSync,
	lchmodAsync,
	lchmodSync,
	lchownAsync,
	lchownSync,
	linkAsync,
	linkSync,
	lstatAsync,
	lstatSync,
	lutimesAsync,
	lutimesSync,
	mkdirAsync,
	mkdirSync,
	mkdirpAsync,
	mkdirpSync,
	mkdirsAsync,
	mkdirsSync,
	mkdtempAsync,
	mkdtempSync,
	mkdtempDisposableAsync,
	mkdtempDisposableSync,
	moveAsync,
	moveSync,
	openAsync,
	openSync,
	openAsBlobAsync,
	openAsHandleAsync,
	openDirAsync,
	openDirSync,
	opendirAsync,
	opendirSync,
	outputFileAsync,
	outputFileSync,
	outputJSONAsync,
	outputJSONSync,
	outputJsonAsync,
	outputJsonSync,
	pathExistsAsync,
	pathExistsSync,
	readAsync,
	readSync,
	readdirAsync,
	readdirSync,
	readFileAsync,
	readFileSync,
	readJSONAsync,
	readJSONSync,
	readJsonAsync,
	readJsonSync,
	readlinkAsync,
	readlinkSync,
	readvAsync,
	readvSync,
	realpathAsync,
	realpathSync,
	removeAsync,
	removeSync,
	renameAsync,
	renameSync,
	rmAsync,
	rmSync,
	rmdirAsync,
	rmdirSync,
	statAsync,
	statSync,
	statfsAsync,
	statfsSync,
	symlinkAsync,
	symlinkSync,
	touchAsync,
	touchSync,
	truncateAsync,
	truncateSync,
	unlinkAsync,
	unlinkSync,
	utimesAsync,
	utimesSync,
	walkAsync,
	walkSync,
	writeAsync,
	writeSync,
	writevAsync,
	writevSync,
	writeFileAsync,
	writeFileSync,
	writeJSONAsync,
	writeJSONSync,
	writeJsonAsync,
	writeJsonSync,
};
