/* eslint-disable import/order,import/no-duplicates */
import {
	type PlatformPath,
	absolute,
	delimiter,
	isAbsolute,
	join,
	leafExt,
	leafName,
	matchesGlob,
	normalize,
	isInDir,
	isInDirs,
	isSafePath,
	isSafeSegment,
	parentName,
	parentPath,
	relative,
	resolve,
	sanitize,
	separator,
	untildify,
} from '@zokugun/fs-path';
import { createReadStream } from './create-read-stream/index.js';
import { createWriteStream } from './create-write-stream/index.js';
import * as globber from './globber/index.js';
import { isFsError } from './is-fs-error/index.js';
import { stringifyJSON, stringifyJson } from './stringify-json/index.js';
import { stripBOM, stripBom } from './strip-bom/index.js';
import { Dir } from './types/dir.js';
import { typeExports } from './types/exports.js';
import type { FsResult, FsVoidResult } from './types/exports.js';
import { FsError } from './types/fs-error.js';
import { type ReadStreamOptions, type WriteStreamOptions } from './types/stream.js';
import { type StringifyJsonOptions } from './types/stringify-json.js';
import { type WalkItem, type WalkOptions } from './types/walk.js';

import {
	access,
	appendFile,
	chmod,
	chown,
	close,
	copyFile,
	cp,
	exists,
	fchmod,
	fchown,
	fdatasync,
	fstat,
	fsync,
	ftruncate,
	futimes,
	glob,
	lchmod,
	lchown,
	link,
	lstat,
	lutimes,
	mkdir,
	mkdtemp,
	mkdtempDisposable,
	open,
	read,
	readv,
	readFile,
	readdir,
	readlink,
	realpath,
	rename,
	rm,
	rmdir,
	stat,
	statfs,
	symlink,
	truncate,
	unlink,
	utimes,
	write,
	writev,
	writeFile,
} from './fs/sync.js';
import { copy } from './copy/sync.js';
import { createFile, ensureFile } from './create-file/sync.js';
import { createLink, ensureLink } from './create-link/sync.js';
import { createSymlink, ensureSymlink } from './create-symlink/sync.js';
import { emptyDir, emptydir } from './empty-dir/sync.js';
import { ensureDir, mkdirp, mkdirs } from './ensure-dir/sync.js';
import { isDir } from './is-dir/sync.js';
import { isEmptyDir } from './is-empty-dir/sync.js';
import { isEmptyFile } from './is-empty-file/sync.js';
import { isExisting } from './is-existing/sync.js';
import { isFile } from './is-file/sync.js';
import { isLink } from './is-link/sync.js';
import { isNonEmptyDir } from './is-non-empty-dir/sync.js';
import { isNonEmptyFile } from './is-non-empty-file/sync.js';
import { isSymlink } from './is-symlink/sync.js';
import { makeTempDir } from './make-temp-dir/sync.js';
import { makeTempFile } from './make-temp-file/sync.js';
import { move } from './move/sync.js';
import { openDir, opendir } from './open-dir/sync.js';
import { outputFile } from './output-file/sync.js';
import { outputJSON, outputJson } from './output-json/sync.js';
import { outputTempFile } from './output-temp-file/sync.js';
import { pathExists } from './path-exists/sync.js';
import { readJSON, readJson } from './read-json/sync.js';
import { remove } from './remove/sync.js';
import { touch } from './touch/sync.js';
import { walk } from './walk/sync.js';
import { writeJSON, writeJson } from './write-json/sync.js';

const gb = globber;

/* eslint-disable unicorn/prefer-export-from */
export {
	type FsResult,
	type FsVoidResult,
	type PlatformPath,
	type ReadStreamOptions,
	type StringifyJsonOptions,
	type WriteStreamOptions,
	type WalkItem,
	type WalkOptions,
	Dir,
	FsError,
	absolute,
	access,
	appendFile,
	chmod,
	chown,
	close,
	copy,
	copyFile,
	cp,
	createFile,
	createLink,
	createReadStream,
	createSymlink,
	createWriteStream,
	delimiter,
	emptyDir,
	emptydir,
	ensureDir,
	ensureFile,
	ensureLink,
	ensureSymlink,
	exists,
	fchmod,
	fchown,
	fdatasync,
	fstat,
	fsync,
	ftruncate,
	futimes,
	gb,
	glob,
	globber,
	isAbsolute,
	isDir,
	isEmptyDir,
	isEmptyFile,
	isExisting,
	isFile,
	isFsError,
	isInDir,
	isInDirs,
	isLink,
	isNonEmptyDir,
	isNonEmptyFile,
	isSafeSegment,
	isSafePath,
	isSymlink,
	join,
	lchmod,
	lchown,
	leafExt,
	leafName,
	link,
	lstat,
	lutimes,
	makeTempDir,
	makeTempFile,
	matchesGlob,
	mkdir,
	mkdirp,
	mkdirs,
	mkdtemp,
	mkdtempDisposable,
	move,
	normalize,
	open,
	openDir,
	opendir,
	outputFile,
	outputJSON,
	outputJson,
	outputTempFile,
	parentName,
	parentPath,
	pathExists,
	read,
	readdir,
	readFile,
	readJSON,
	readJson,
	readlink,
	readv,
	realpath,
	relative,
	remove,
	rename,
	resolve,
	rm,
	rmdir,
	sanitize,
	separator,
	stat,
	statfs,
	stringifyJSON,
	stringifyJson,
	stripBOM,
	stripBom,
	symlink,
	touch,
	truncate,
	unlink,
	untildify,
	utimes,
	walk,
	write,
	writev,
	writeFile,
	writeJSON,
	writeJson,
};
/* eslint-enable unicorn/prefer-export-from */

// eslint-disable-next-line @typescript-eslint/consistent-type-imports
const defaultExport: Omit<typeof import('./sync.js'), 'default'> = {
	...typeExports,
	Dir,
	FsError,
	absolute,
	access,
	appendFile,
	chmod,
	chown,
	close,
	copy,
	copyFile,
	cp,
	createFile,
	createLink,
	createReadStream,
	createSymlink,
	createWriteStream,
	delimiter,
	emptyDir,
	emptydir,
	ensureDir,
	ensureFile,
	ensureLink,
	ensureSymlink,
	exists,
	fchmod,
	fchown,
	fdatasync,
	fstat,
	fsync,
	ftruncate,
	futimes,
	gb,
	glob,
	globber,
	isAbsolute,
	isDir,
	isEmptyDir,
	isEmptyFile,
	isExisting,
	isFile,
	isFsError,
	isInDir,
	isInDirs,
	isLink,
	isNonEmptyDir,
	isNonEmptyFile,
	isSafeSegment,
	isSafePath,
	isSymlink,
	join,
	lchmod,
	lchown,
	leafExt,
	leafName,
	link,
	lstat,
	lutimes,
	makeTempDir,
	makeTempFile,
	matchesGlob,
	mkdir,
	mkdirp,
	mkdirs,
	mkdtemp,
	mkdtempDisposable,
	move,
	normalize,
	open,
	openDir,
	opendir,
	outputFile,
	outputJSON,
	outputJson,
	outputTempFile,
	parentName,
	parentPath,
	pathExists,
	read,
	readdir,
	readFile,
	readJSON,
	readJson,
	readlink,
	readv,
	realpath,
	relative,
	remove,
	rename,
	resolve,
	rm,
	rmdir,
	sanitize,
	separator,
	stat,
	statfs,
	stringifyJSON,
	stringifyJson,
	stripBOM,
	stripBom,
	symlink,
	touch,
	truncate,
	unlink,
	untildify,
	utimes,
	walk,
	write,
	writev,
	writeFile,
	writeJSON,
	writeJson,
};

export default defaultExport;
